pipeline:
  name: ecs_win
  identifier: ecs_win
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ecs-win
        identifier: ecswin
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: Createecs_win
                  identifier: Createecs_win
                  spec:
                    provisionerIdentifier: ecswin
                    configuration:
                      stackName: ecswin
                      connectorRef: AWSconnector
                      region: ap-south-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - ecs_win.yaml
                              connectorRef: githarness
                              repoName: Harness
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: Subnet1
                          value: subnet-06e299a94069f053c
                          type: String
                        - name: Subnet2
                          value: subnet-069a39317ef4dbbbe
                          type: String
                        - name: ServiceName
                          value: ecsnew
                          type: String
                        - name: ECSClusterName
                          value: ecsclustere
                          type: String
                        - name: VPC
                          value: vpc-063e42b23f2d4fe43
                          type: String
                  timeout: 10m
        tags: {}
