pipeline:
  name: eks-parameterise
  identifier: eksparameterise
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: create-eks
        identifier: createeks
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateEKS
                  identifier: CreateEKS
                  spec:
                    provisionerIdentifier: eksnew
                    configuration:
                      stackName: eksand
                      connectorRef: AWSconnector
                      region: ap-south-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - eks.yaml
                              connectorRef: githarness
                              repoName: Harness
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: NumWorkerNodes
                          value: "2"
                          type: String
                        - name: KeyPairName
                          value: eks-test
                          type: String
                        - name: EKSClusterName
                          value: <+input>
                          type: String
                        - name: WorkerNodesInstanceType
                          value: t3a.medium
                          type: String
                  timeout: 10m
        tags: {}
