pipeline:
  name: s3-ecs
  identifier: s3ecs
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ecss3
        identifier: ecss3
        description: ""
        type: Deployment
        spec:
          deploymentType: ECS
          service:
            serviceRef: ecs
          environment:
            environmentRef: Dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: ecsinfra
                inputs:
                  identifier: ecsinfra
                  type: ECS
                  spec:
                    cluster: <+input>
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: ecss3
                    configuration:
                      stackName: ecs-lamda-s3
                      connectorRef: AWSconnector
                      region: ap-south-1
                      templateFile:
                        type: Remote
                        spec:
                          store:
                            type: Github
                            spec:
                              paths:
                                - ecs-lamda-s3.yaml
                              connectorRef: githarness
                              repoName: Harness
                              gitFetchType: Branch
                              branch: main
                      roleArn: ""
                      parameterOverrides:
                        - name: Subnet1
                          value: subnet-06e299a94069f053c
                          type: String
                        - name: Subnet2
                          value: subnet-0aab1ca587be08d40
                          type: String
                        - name: ServiceName
                          value: testecsnew
                          type: String
                        - name: ECSClusterName
                          value: testecss3clst
                          type: String
                        - name: VPC
                          value: vpc-063e42b23f2d4fe43
                          type: String
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
