pipeline:
  name: test-ci
  identifier: testci
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: Azure-Samples/dotnetcore-docs-hello-world
        build: <+input>
  stages:
    - stage:
        name: build-akage
        identifier: buildakage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerharness
                    repo: amoldorkhande
                    tags:
                      - dockerbuild
                    dockerfile: Dockerfile.linux
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
